### ISSUE TITLE
Global error handler

### ISSUE THREAD

**Issue by zeeshanok** [gurkult/gurkbot#29]
Our bot needs a global error handler to help out the user when they make common mistakes like `MissingRequiredArgument`, `BadArgument` and `MissingPermissions` etc.

**Comment by zeeshanok** [comment]
I _can_ do this but I will be busy these few days so if someone would take it on, that would be nice 😅

**Comment by gustavwilliam** [comment]
As a base for this error handler, we could probably use some parts of https://github.com/python-discord/bot/blob/master/bot/exts/backend/error_handler.py. I think that error handler is well written and should have a lot of what we're looking for.

This is a high priority issue, since a solid error handler is the foundation of any great bot.

**Comment by Shivansh-007** [comment]
Will do it.

**Comment by Shivansh-007** [comment]
We can close this now.

**Comment by gustavwilliam** [comment]
Excellent. Thanks!
